In [1]:
import pandas as pd

In [2]:
# Ejemplo: definir manualmente tipos de columnas

df = pd.read_csv('../datasets/dt_target.csv', sep=',')

In [3]:
from reducirDT import optimize_memory_usage
df = optimize_memory_usage(df)

Memoria inicial: 4976.40 MB
Memoria final:   794.34 MB
Reducción:       84.04%

In [39]:
df = pd.read_csv('../datasets/sell-in.txt.gz',sep='\t')
ventas_diciembre = df[df['periodo'] == 201912].copy()

In [40]:
# promedio 3,6,9,12
# multiplicar x0.98,0.99,1.01,1.02


periodos = df.periodo.unique()
periodos.sort()
promedio3 = df[df['periodo'].isin(periodos[-3:]) ].copy()
promedio6 = df[df['periodo'].isin(periodos[-6:]) ].copy()
promedio9 = df[df['periodo'].isin(periodos[-9:]) ].copy()
promedio12 = df[df['periodo'].isin(periodos[-12:]) ].copy()

In [41]:
productos_ok = pd.read_csv("https://storage.googleapis.com/open-courses/austral2025-af91/labo3v/product_id_apredecir201912.txt", sep="\t")

r_diciembre = ventas_diciembre[["product_id", "tn"]].copy()
r_diciembre = r_diciembre[r_diciembre["product_id"].isin(productos_ok["product_id"])]
r_diciembre = r_diciembre.groupby("product_id").agg({"tn":"sum"}).reset_index()
r_diciembre.to_csv("../results/trivial_diciembre.csv", index=False)

In [42]:
r_diciembre

     product_id          tn
0         20001  1504.68856
1         20002  1087.30855
2         20003   892.50129
3         20004   637.90002
4         20005   593.24443
..          ...         ...
775       21263     0.01270
776       21265     0.05007
777       21266     0.05121
778       21267     0.01569
779       21276     0.00892

[780 rows x 2 columns]

In [52]:
# promedio 3
r = promedio3.copy()
r = r.groupby(["periodo","product_id"]).agg({"tn":"sum"}).reset_index()
r = r.groupby(["product_id"]).agg({"tn":"mean"}).reset_index()
r = r[r["product_id"].isin(productos_ok["product_id"])]
r3 = r.groupby("product_id").agg({"tn":"sum"}).reset_index()
r3.to_csv("../results/promedio3.csv", index=False)

In [54]:
# promedio 6
r = promedio6.copy()
r = r.groupby(["periodo","product_id"]).agg({"tn":"sum"}).reset_index()
r = r.groupby(["product_id"]).agg({"tn":"mean"}).reset_index()
r = r[r["product_id"].isin(productos_ok["product_id"])]
r6 = r.groupby("product_id").agg({"tn":"sum"}).reset_index()
r6.to_csv("../results/promedio6.csv", index=False)
r6

     product_id           tn
0         20001  1510.651745
1         20002  1243.473690
2         20003   873.455267
3         20004   702.759787
4         20005   726.480795
..          ...          ...
775       21263     0.023287
776       21265     0.047978
777       21266     0.056508
778       21267     0.047722
779       21276     0.016093

[780 rows x 2 columns]

In [55]:
# promedio 9
r = promedio9.copy()
r = r.groupby(["periodo","product_id"]).agg({"tn":"sum"}).reset_index()
r = r.groupby(["product_id"]).agg({"tn":"mean"}).reset_index()
r = r[r["product_id"].isin(productos_ok["product_id"])]
r9 = r.groupby("product_id").agg({"tn":"sum"}).reset_index()
r9.to_csv("../results/promedio9.csv", index=False)
r9

     product_id           tn
0         20001  1494.585441
1         20002  1190.202131
2         20003   784.286781
3         20004   661.530294
4         20005   750.838167
..          ...          ...
775       21263     0.021170
776       21265     0.097720
777       21266     0.103280
778       21267     0.079174
779       21276     0.036887

[780 rows x 2 columns]

In [56]:
# promedio 12
r = promedio12.copy()
r = r.groupby(["periodo","product_id"]).agg({"tn":"sum"}).reset_index()
r = r.groupby(["product_id"]).agg({"tn":"mean"}).reset_index()
r = r[r["product_id"].isin(productos_ok["product_id"])]
r12 = r.groupby("product_id").agg({"tn":"sum"}).reset_index()
r12.to_csv("../results/promedio12.csv", index=False)
r12

     product_id           tn
0         20001  1454.732720
1         20002  1175.437142
2         20003   784.976407
3         20004   627.215328
4         20005   668.270104
..          ...          ...
775       21263     0.029993
776       21265     0.089541
777       21266     0.094659
778       21267     0.092835
779       21276     0.045447

[780 rows x 2 columns]

In [57]:
val = [0.98, 0.99, 1.01, 1.02]
for v in val:
    r3["tn"] = r3["tn"] * v
    r6["tn"] = r6["tn"] * v
    r9["tn"] = r9["tn"] * v
    r12["tn"] = r12["tn"] * v

    r3.to_csv(f"../results/promedio3_{v}.csv", index=False)
    r6.to_csv(f"../results/promedio6_{v}.csv", index=False)
    r9.to_csv(f"../results/promedio9_{v}.csv", index=False)
    r12.to_csv(f"../results/promedio12_{v}.csv", index=False)